config/routes.rb
SampleApp::Application.routes.draw do
  resources :maps

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/susisiekite', to: 'static_pages#susisiekite', via: 'get'

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:address, :lng, :lat)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end

  def susisiekite
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "DVD nuoma"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <b>UAB &quot;Samarina&quot; E. Šimkūnaitės g. 10, Vilnius, Lietuva; tel. +370 5 2392182</b>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Apie",   about_path %></li>
      <li><%= link_to "Kontaktai", contact_path %></li>
      <li><a href="http://www.cargonews.lt/">Naujienos</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner" >
  <table class="style2" float="left"> <tr>
<td>
   <%= link_to (image_tag("logo.bmp", :alt => "„Samarina“")), root_path %>
</td>
</tr>
</table>
        <ul class="nav pull-right">
          <li><%= link_to "Titulinis",  root_path %></li>
          <li><%= link_to "Paslaugos",  help_path %></li>
          <li><%= link_to "Susiekite", susisiekite_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;
key=ABQIAAAAuPsJpk3MBtDpJ4G8cqBnjRRaGTYH6UMl8mADNa0YKuWNNa8VNxQCzVBXTx2DYyXGsTOxpWhvIG7Djw"
 type="text/javascript"></script>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
        <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Lng</th>
      <th>Lat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.address %></td>
        <td><%= map.lng %></td>
        <td><%= map.lat %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @map.address %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @map.lng %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @map.lat %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="center hero-unit">
<h1>Apie mus</h1>
<p><h3>UAB „Samarina“ pradėjo savo veiklą dar prieš 20 metų, ir iki šiol sėkmingai vykdome ir turime didelį laimingų klientų ratą. Mes esame tikrieji LINAVA nariai.</h3></p>
<p><h3>Mūsų pagrindinė veikla - tarptautiniai krovinių pervežimai tentinėmis puspriekabėmis sausuma ir ekspedijavimo paslaugos. Turime patikimus, tarptautinį vardą turinčius partnerius, su kurių pagalba padėsime saugiai ir greitai pristatyti Jūsų krovinį iš taško A į tašką B.</h3></p> 
<p><b>Mūsų įmonė - tai..</b></p>
<ul class="a">
<li><b>Rimtas ir atsakingas požiūris į darbą!</b> Dirbame, jog maksimaliai patenkintume kliento poreikius
<li><b>Naujas ir patikimas vilkikų parkas su kvalifikuotais vairuotojais!</b> Kiekvienais metais atnaujiname vilkiku ir puspriekabių parką, tuo garantuodami technikos patikimumą ir saugumą kelyje ir taip pat prisidedami prie aplinkos apsaugos, nes vilkikai atitinka naujausius oro taršos reikalavimus
<li><b>Patikimi darbuotojai!</b> Vairuotojams reguliariai rengiame ekologiško ir saugaus vairavimo kursus, tuom prisidedami prie aplinkos apsaugos. Darbuotojų kaita yra maža, ir tai padeda išlaikyti ilgalaikį profesionalų servisą
<li><b>Moderni informacinė sistema!</b> Naudojame naujausias technologijas, padedančias efektyviausiai suteikti informaciją klientui pradedant nuo 24/7 automobilių stebėjimo, perduodant klientui nuorodą iki elektoroninių sąskaitu ir pervežimo dokumentų pateikimo iškarto po krovinio pristatymo
<li><b>Draudimas ir garantijos</b> Mūsų visas parkas apdraustas KASKO ir civiline atsakomybę, kroviniai apdrausti Vežėjo civilinės atsakomybes (CMR) draudimu.
<li><b>Sąžiningas ir ilgalaikis požiūris į kainas!</b> Galime pasiūlyti ilgalaikes pervežimo kainas, neatsižvelgiant į sezoniškumą, garantuodami geriausią servisą </ul></h3></p>
<p><h1> Dirbame Jums! </h1></p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="center hero-unit">
<h1>Kontaktai ir rekvizitai</h1>
<p><div align=left><b> UAB &quot;Samarina&quot;</b></div>
<div align=left>E. Šimkūnaitės g. 10</div>
<div align=left>LT-04130 Vilnius, Lietuva</div>
<div align=left>Tel. +370 5 2392182 </div>
<div align=left>Faks. +370 5 2392183</div>
<div align=left>El. paštas <a href="mailto:info@samarina.lt">info@samarina.lt</a></div>
<div align=left>Įmonės kodas 122602672</div>
<div align=left>PVM kodas LT226026716</div>
<div align=left>a/s LT107300010002480942</div>
<div align=left>AB Swedbank</div> 
<br></p>
<div align=left><b>Kontaktai:</b></div>
<br>
<div align=left><b>Direktorius</b></div>
<div align=left>Alfredas Pacevičius</div>
<div align=left>+370 5 2392182</div>
<div align=left>El. paštas <a href="mailto:alfredas.pacevicius@samarina.lt">alfredas.pacevicius@samarina.lt</a></div>
<br>
<div align=left><b>Direktoriaus pavaduotojas</b></div>
<div align=left>Audrius Mikalauskas</div>
<div align=left>+370 5 2392182</div>
<div align=left>El. paštas <a href="mailto:audrius.mikalauskas@samarina.lt">audrius.mikalauskas@samarina.lt</a></div>
<br>
<div align=left><b>Pardavimų vadovė</b></div>
<div align=left>Rasa Skiparytė-Pocienė</div>
<div align=left>+370 618 45547</div>
<div align=left>El. paštas <a href="mailto:rasa@samarina.lt">rasa@samarina.lt</a></div>
<br>
<div align=left><b>Vadybininkas (tansportas)</b></div>
<div align=left>Joanas Kaminskas</div>
<div align=left>+370 614 246047</div>
<div align=left>El. paštas <a href="mailto:joanas@samarina.lt">joanas@samarina.lt</a></div>
<br>
<div align=left><b>Vadybininkas (transporto priežiūra ir
techninis aptarnavimas)</b></div>
<div align=left>Arūnas Nečiūnas</div>
<div align=left>+370 610 76768</div>
<div align=left>El. paštas <a href="mailto:arunas@samarina.lt">arunas@samarina.lt</a></div>
<br>
<div align=left><b>Ekspedicijos vadybininkas</b></div>
<div align=left>Justinas Mažuika</div>
<div align=left>+370 655 98718</div>
<div align=left>El. paštas <a href="mailto:justinas@samarina.lt">justinas@samarina.lt</a></div>
<br>
<div align=left><b>Administratorė-vadybininkė</b></div>
<div align=left>Ieva Pukelytė-Každailienė</div>
<div align=left>+370 5 2392182</div>
<div align=left>El. paštas <a href="mailto:ieva.pukelyte@samarina.lt">ieva.pukelyte@samarina.lt</a></div>
<br>
<div align=left><b>Vyr. buhalterė</b></div>
<div align=left>Tamara Gaisionok</div>
<div align=left>+370 5 2392182</div>
<div align=left>El. paštas <a href="mailto:buhalterija@samarina.lt">buhalterija@samarina.lt.lt</a></div>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="center hero-unit">
<h1>Paslaugos</h1>
<br><p>Šiuo metu turime 45-is vilkikus iš kurių 20 važinėja reguliariais maršrutais Lietuva - ES įvairios šalys. Likę 25-i vilkikai važiuoja 1,5 mėnesio maršrutams po ES šalis. Vilkikai, kurie važiuoja maršrutais Lietuva - ES šalys, turi bortines 92m<sup>3</sup> puspriekabes. Taipogi jos gali krautis per viršų ir šoną.</p>
<table align="center"> <tr>
<td>
   <%= image_tag("bortas.jpg", :alt => "„Bortinė puspriekabė“") %>
</td>
</tr>
</table>
<br><p>Turime dvi „dvigubo dugno“ puspriekabes, kurios puikiai tinka nedidelio aukščio ir svorio krovinias arba rinktiniams kroviniams.</p>
<table align="center"> <tr>
<td>
   <%= image_tag("doubledeck.jpg", :alt => "„Dvigubo dugno puspriekabė“") %>
</td>
</tr>
</table>
<br><p>Vilkikai, dirbantys po ES šalis, turi užuolaidines puspriekabes. Jos taip pat gali krautis per viršų ir šoną.</p> 
<table align="center"> <tr>
<td>
   <%= image_tag("uzuolaida.jpg", :alt => "„Užuolaidinė puspriekabė“") %>
</td>
</tr>
</table>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
 
  <h2><p class="serif">UAB &quot;Samarina&quot; yra transporto įmonė, 2014 metais šventusi savo 20-metį. Įmonė turi 45-is vilkikus. Du trečdaliai vilkikų atitinka EURO4 ir EURO5 klases. Per ilgus įmonės gyvavimo metus specializavomės tarptautiniuose pervežimuose tarp Lietuvos ir Lenkijos, Vokietijos, Italijos, Šveicarijos, Čekijos, Belgijos, Olandijos. Galime pasiūlyti nuosavą transportą, taip pat ir partnerių tranportą ir terminalus. Sėkmingai dirbame vidiniais maršrutais po ES šalis.</p></h2>
<table class="style1" align="center"> <tr>
<td>
   <%= image_tag("samarina1.jpg", :alt => "„Samarina“") %>
</td>
</tr>
</table>

 </div>

app/views/static_pages/susisiekite.html.erb
<% provide(:title, 'susisiekite') %>
<h1>Susisiekite</h1>
<p>
  Susisiekite su mumis jei norite pervežti krovinį:</p>
  <form method="post" action="mailto:joanas.kaminskas@gmail.com">
<p>Jūsų vardas: <input type="text" name="Vardas" size="20" maxlength="80"> </p>
<p>Elektroninis pašto adresas: <input type="text" name="Elektroninis pašto adresas" size="20" maxlength="80"> </p>
<p><textarea align="left"; cols="40"; rows="5";>Įrašykite savo užklausą čia...
 </textarea></p>
 <p><input type="submit" name="ok" value="Siųsti"><input type="reset" name="Atšaukti" value="Atšaukti"></p>
</form>
</p>